apiVersion: v1
kind: Secret
metadata:
  namespace: capp
  name: capp-cfg
  annotations:
    avp.kubernetes.io/path: data/argocd/cert-app
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  PASS: <PASS>
---
apiVersion: v1
kind: Secret
metadata:
  namespace: capp
  name: capp-cert
  annotations:
    avp.kubernetes.io/path: data/argocd/cert-app
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  cert.crt: <cert.crt>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capp-main
  namespace: capp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capp-main
  template:
    metadata:
      labels:
        app: capp-main
    spec:
      containers:
      - name: test-container
        image: fedora:39
        env:
          - name: AUTHOR
            value: IraMeis
        envFrom:
          - configMapRef:
              name: capp-cfg
        volumeMounts:
          - name: cert-volume
            mountPath: "/app/certificates"
            readOnly: true
      volumes:
        - name: cert-volume
          projected:
            sources:
              - secret:
                  name: capp-cert
