apiVersion: v1
kind: Secret
metadata:
  name: auth-helm
type: Opaque
data:
  {{- with secret "avp/data/example/example-auth" }}
  {{- range $k, $v := .Data }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
  {{- end }}
