apiVersion: v1
kind: Secret
metadata:
  name: auth-helm
  annotations:
    avp.kubernetes.io/path: avp/data/example/example-auth
type: Opaque
stringData:
  username: Administrator
  password: <password>
