apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-vault-demo.fullname" . }}
  annotations:
    avp.kubernetes.io/path: avp/data/example/example-auth
type: Opaque
stringData:
  username: Administrator
  password: <password>
